#!/bin/sh
# vim: ts=8:sw=8:sts=8:noet:ft=sh
# -*- mode: sh; tab-width: 2; indent-tabs-mode: nil; -*-
#
# GNU General Public License v3.0+
# SPDX-License-Identifier: GPL-3.0-or-later
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
#
# Copyright (c) 2025 oØ.o (@o0-o)
#
# This file is part of the o0_o.posix Ansible Collection.
#
# Setup script for Linux containers in CI to install pyenv and Python versions

# Install build dependencies for pyenv based on Linux distribution
case "$LINUX_OS" in
	debian:*|ubuntu:*)
		export DEBIAN_FRONTEND=noninteractive
		export TZ=UTC
		apt-get update -qq &&
		apt-get dist-upgrade -y -qq &&
		apt-get install -y -qq \
			-o Dpkg::Options::="--force-confdef" \
			-o Dpkg::Options::="--force-confold" \
			bash git curl tar findutils build-essential \
			libssl-dev zlib1g-dev libbz2-dev libreadline-dev \
			libsqlite3-dev libncursesw5-dev xz-utils tk-dev \
			libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev \
			libyaml-dev locales shellcheck openssh-client rsync
		# Generate en_US.UTF-8 locale
		echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
		locale-gen
		update-locale LANG=en_US.UTF-8
		;;
	fedora:*|*rockylinux:*|almalinux:*|*centos*)
		# Enable EPEL for RHEL-based distros (not needed for Fedora)
		case "$LINUX_OS" in
			fedora:*)
				# Fedora has ShellCheck in main repos
				;;
			*)
				# All other RPM distros need EPEL
				dnf install -y -q --allowerasing epel-release
				;;
		esac
		dnf update -y -q &&
		# Install shared packages
		dnf install -y -q --allowerasing \
			bash git curl tar findutils gcc make openssl-devel \
			bzip2-devel libffi-devel zlib-devel readline-devel \
			sqlite-devel xz-devel glibc-langpack-en \
			openssh-clients ShellCheck rsync
		# Install distro-specific YAML package
		case "$LINUX_OS" in
			fedora:*)
				dnf install -y -q --allowerasing libyaml-devel
				;;
			*)
				# Rocky/CentOS/AlmaLinux don't have
				# libyaml-devel or yaml-devel PyYAML will be
				# installed via pip, so this is optional
				echo "Skipping YAML devel package (not " \
					"available on this distro)"
				;;
		esac
		;;
	opensuse/*)
		zypper update -y &&
		zypper install -y \
			bash git curl tar gzip findutils gcc make \
			openssl-devel libbz2-devel libffi-devel zlib-devel \
			readline-devel sqlite3-devel xz-devel libyaml-devel \
			gawk coreutils glibc-locale ShellCheck openssh rsync
		;;
	archlinux)
		pacman -Syu --noconfirm --quiet &&
		pacman -S --noconfirm --quiet \
			bash git curl tar findutils base-devel openssl zlib \
			bzip2 libffi readline sqlite xz libyaml shellcheck \
			openssh rsync
		;;
	alpine:*)
		apk update --quiet &&
		apk upgrade --quiet &&
		apk add --no-cache --quiet \
			bash git curl tar findutils build-base openssl-dev \
			zlib-dev bzip2-dev libffi-dev readline-dev sqlite-dev \
			xz-dev yaml-dev coreutils shellcheck openssh-client \
			rsync
		;;
esac

# Set locale to avoid ansible-test warnings (after locale packages are
# installed)
# Alpine uses musl and doesn't have traditional locale support
# Arch doesn't have en_US.UTF-8 generated by default
case "$LINUX_OS" in
	alpine:*|archlinux)
		export LANG=C.UTF-8
		export LC_ALL=C.UTF-8
		echo "export LANG=C.UTF-8" >> /root/.profile
		echo "export LC_ALL=C.UTF-8" >> /root/.profile
		;;
	*)
		export LANG=en_US.UTF-8
		export LC_ALL=en_US.UTF-8
		echo "export LANG=en_US.UTF-8" >> /root/.profile
		echo "export LC_ALL=en_US.UTF-8" >> /root/.profile
		;;
esac

# Install pyenv system-wide
export PYENV_ROOT="/opt/pyenv"
curl -s https://pyenv.run | bash >/dev/null
export PATH="/opt/pyenv/bin:${PATH}"
eval "$(pyenv init - sh)" >/dev/null

# Install the specific Python version from environment variable
pyenv install "${PYTHON_VERSION}" >/dev/null
pyenv global "${PYTHON_VERSION}"

# Refresh pyenv shims
mkdir -p "$(pyenv root)/plugins"
git clone https://github.com/pyenv/pyenv-which-ext.git \
	"$(pyenv root)/plugins/pyenv-which-ext" >/dev/null
pyenv rehash

# Create venv with latest Python and install ansible-core
git config --global --add safe.directory '*'

python -m venv .venv
. .venv/bin/activate
pip install --quiet --upgrade pip
pip install --quiet ansible-core
